name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/base.yml
    secrets: inherit

  tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
